# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Check

on:

  push:
    branches: [ main, master, dev ]
    paths:
      - '**.py'
  pull_request:
    branches: [ main, master ]

jobs:

  Check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker://continuumio/miniconda3
      - name: Updating conda
        run: conda update --all -y
      - name: Installing make
        run: conda install -y make
      - name: Checkout CI/CD Toolkit
        uses: actions/checkout@v2
        with:
          repository: breakthewall/cicd-toolkit
          path: cicd-toolkit
          persist-credentials: false
          fetch-depth: 0
      - name: Checking package
        run: |
          cd cicd-toolkit
          make check-buildenv env=check
          conda run -n check make check
